<header class="flex-shrink-0">
    <nav class="navbar navbar-expand-md navbar-dark bg-dark px-3">
        <a class="navbar-brand" href="<?= $urlFor('home') ?>">Анализатор страниц</a>
        <button
            class="navbar-toggler"
            type="button"
            data-bs-toggle="collapse"
            data-bs-target="#navbarNav"
            aria-controls="navbarNav"
            aria-expanded="false"
            aria-label="Toggle navigation"
        >
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link <?= $activePage === 'home' ? 'active' : '' ?>"
                        href="<?= $urlFor('home') ?>">
                        Главная
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link <?= $activePage === 'urls.index' ? 'active' : '' ?>"
                        href="<?= $urlFor('urls.index') ?>">
                        Сайты
                    </a>
                </li>
            </ul>
        </div>
    </nav>
</header>
